### ISSUE TITLE
Add service to the CLI

### ISSUE THREAD

**Issue by christian-bromann** [elaichenkov/wdio-wait-for#1]
Hey 👋 

first of: great package! This will be especially helpful for Protractor users who have been using expected conditions like that.

I have one request: for better discoverability of this service, would you mind adding it to the CLI? Just raise a PR similar to https://github.com/webdriverio/webdriverio/pull/6668/files

What do you think?

**Comment by elaichenkov** [comment]
Hey!
Sure, done. Please, check [it](https://github.com/webdriverio/webdriverio/pull/6732) out.

**Comment by christian-bromann** [comment]
Thank you!

**Comment by christian-bromann** [comment]
Your docs are now available on the WebdriverIO website: https://webdriver.io/docs/wdio-wait-for. I will have to re-trigger the deployment to get your recent updates.
