### ISSUE TITLE
Alignment with Protractors Expected Conditions

### ISSUE THREAD

**Issue by christian-bromann** [elaichenkov/wdio-wait-for#2]
Hey,

how about aligning some of the expected conditions with the ones [Protractor](https://www.protractortest.org/#/api?view=ProtractorExpectedConditions) has. One reason for that is that Protractor is [being discontinued](https://github.com/angular/protractor/issues/5502) and it would help a lot of users that make the transition to WebdriverIO to just swap in this service and keep their tests as is. I then could [update the codemod](https://github.com/webdriverio/codemod/blob/main/protractor/index.js#L667-L692) to notify users to use this service. That would be a nice drop in replacement.

What do you think?

**Comment by elaichenkov** [comment]
Hey again!

Yep, I thought about that but decided to name some methods more meaningful than protractor's conditions. But, totally agree with you, that could help a ton of users to make migration easier.

I'll align them.

**Comment by christian-bromann** [comment]
@elaichenkov I don't mind keeping the current ones as they are. Maybe there can just be an alias.

**Comment by elaichenkov** [comment]
Done.

Now, in the 2.0.2 version, all methods are aligned with the protractor's methods.

**Comment by christian-bromann** [comment]
That's amazing, great work! I will get the codemod updated within the next days. Thanks a lot!
